package main

import (
	"embed"
	"fmt"
	"strings"
)

//go:embed content/blog
var blogFS embed.FS

type post struct {
	title string
	date  string
	slug  string
}

var posts = []post{
	{title: "I built a benchmark to find out which code graph actually understands your codebase", date: "2026-08-21", slug: "codegraph-bench"},
}

func loadPost(p post) string {
	b, err := blogFS.ReadFile("content/blog/" + p.slug + ".md")
	if err != nil {
		return fmt.Sprintf("# %s\n\n(post body unavailable)", p.title)
	}
	return stripFrontmatter(string(b))
}

// stripFrontmatter removes a leading YAML frontmatter block (--- ... ---),
// mirroring what src/lib/blog.ts does for the website.
func stripFrontmatter(s string) string {
	if !strings.HasPrefix(s, "---") {
		return s
	}
	if i := strings.Index(s[3:], "\n---"); i >= 0 {
		rest := s[3+i+4:]
		return strings.TrimPrefix(rest, "\n")
	}
	return s
}

type experience struct {
	role, company, period string
	points                []string
}

var experiences = []experience{
	{
		role: "Software Development Intern", company: "Vyazen", period: "May 2026 — Present",
		points: []string{
			"Integrated the OpenCode SDK as an alternative backend to the Claude Agent SDK.",
			"Built a codebase exploration subagent using custom MCPs to improve repository analysis.",
			"Implemented Bitbucket OAuth for codebase integration and Git operations.",
			"Developed a benchmark to compare codebase graphs generated by different developer tools.",
			"Extended model infrastructure with AWS Bedrock support for LLMs, embeddings, and reranking.",
		},
	},
	{
		role: "Open Source Contributor", company: "Zed", period: "Mar 2026 — May 2026",
		points: []string{
			"Accepted into the Zed Guild, collaborating with the core team on real issues in an editor developed openly.",
			"Contributed to globally used developer features while strengthening open-source contribution experience.",
		},
	},
	{
		role: "Software Engineering Intern", company: "Ealana", period: "Jan 2026 — May 2026",
		points: []string{
			"Implemented WhatsApp integration to support parallel email and WhatsApp updates.",
			"Integrated a PostgreSQL/pgvector graph database for searching and sourcing candidates.",
			"Revamped the company’s public pages to improve UX and visual consistency.",
		},
	},
	{
		role: "Software Engineering Intern", company: "Aeternik", period: "Sep 2025 — Jan 2026",
		points: []string{
			"Architected and containerized a microservices-based AI backend using Go, Python, and Docker.",
			"Developed an advanced RAG system for production using a modular framework.",
			"Implemented caching and feedback loops to reduce latency and hallucinations.",
		},
	},
	{
		role: "Software Engineering Intern", company: "NALCO", period: "Jun 2025",
		points: []string{
			"Created an internal RAG tool using a FastAPI/PostgreSQL backend with an HTML/CSS/JavaScript frontend.",
			"Implemented PDF ingestion, chunking, and embedding using Sentence Transformers for vector search.",
		},
	},
	{
		role: "Machine Learning Research Intern", company: "KJSSE", period: "Feb 2025 — Present",
		points: []string{
			"Managed data pipelines for agricultural datasets to support machine learning applications.",
			"Built and optimized predictive machine learning models for accuracy and interpretability.",
		},
	},
	{
		role: "Committee Member", company: "SMLRA", period: "Aug 2024 — May 2025",
		points: []string{
			"Conducted research on legal document summarization.",
			"Contributed to event management and hosting activities.",
			"Created social media series like Fact Friday and ML Monday.",
		},
	},
	{
		role: "Python Developer Intern", company: "Secuodsoft Technologies", period: "Dec 2024",
		points: []string{
			"Developed backend features using Django and MySQL.",
			"Implemented frontend components using JavaScript and Bootstrap.",
			"Managed static and media files for application assets and uploads.",
		},
	},
}

type project struct {
	name  string
	stack string
	points []string
}

var projects = []project{
	{name: "CareerWiki", stack: "Next.js · Tailwind · Gemini API · MongoDB",
		points: []string{
			"AI-powered platform for exploring career paths with interactive simulations and guidance.",
			"Integrated a personalized AI career consultant for tailored advice and analysis.",
			"Server-side logic with Next.js API routes and MongoDB for data storage.",
		}},
	{name: "PropChain", stack: "Python · FastAPI · LangGraph · CopilotKit · Solidity",
		points: []string{
			"Real estate marketplace on blockchain for validating documents and buying/selling land.",
			"Agentic AI chat using LangGraph for interacting with the website.",
			"Facial-recognition based verification using Tesseract.",
		}},
	{name: "RideMates", stack: "React · Node.js · Express · MongoDB · Firebase · Tailwind",
		points: []string{
			"Ride-sharing / carpool platform connecting drivers and riders.",
			"Built authentication, schema design and ride-matching logic.",
			"Enhanced frontend UX with ratings, ride updates and profile management.",
		}},
	{name: "Speech to Insights", stack: "FastAPI · React · Tailwind · OpenAI Whisper",
		points: []string{
			"Minimal frontend converting voice input into text with OpenAI Whisper.",
			"Generated insights via the Hugging Face Inference Client before voice integration in the ChatGPT era.",
		}},
}

var techGroups = []struct {
	name  string
	items []string
}{
	{"Languages", []string{"Python", "C++", "JavaScript", "TypeScript", "Go", "Solidity"}},
	{"Frameworks", []string{"React", "Node.js", "Express", "Next.js", "FastAPI", "Django", "Tailwind CSS"}},
	{"Tools", []string{"Git", "GitHub", "VSCode", "Jupyter", "Docker", "Hardhat", "LangChain"}},
	{"Data", []string{"PostgreSQL", "Weaviate", "Redis", "MongoDB", "pgvector"}},
}

const (
	name     = "Arpit Mishra"
	tagline  = "software engineer"
	bio      = "I build software across the stack — from agentic AI systems and code intelligence tooling to web platforms. Currently interning at Vyazen, contributing to Zed, and studying engineering in Mumbai."
	email    = "mishrarpit3117@gmail.com"
	github   = "github.com/ArpitMishra17"
	linkedin = "linkedin.com/in/arpit-mishra-7a1823277"
	xHandle  = "x.com/0xarpitm"
)
