import { useState } from 'react'
import ScrollReveal from './ScrollReveal'

const experiences = [
  {
    company: 'Vyazen',
    role: 'Software Development Intern',
    period: 'May 2026 — Present',
    current: true,
    desc: 'Integrated the OpenCode SDK as an alternative backend to the Claude Agent SDK.<br/>Built a codebase exploration subagent using custom MCPs to improve repository analysis.<br/>Implemented Bitbucket OAuth for codebase integration and Git operations.<br/>Developed a benchmark to compare codebase graphs generated by different developer tools.<br/>Extended model infrastructure with AWS Bedrock support for LLMs, embeddings, and reranking.',
  },
  {
    company: 'Zed',
    role: 'Open Source Contributor',
    period: 'Mar 2026 — May 2026',
    current: false,
    desc: 'Accepted into the Zed Guild, where I collaborated with the core team to tackle real issues in an editor developed openly.<br/>Contributed to globally used developer features while strengthening my open-source contribution experience.',
  },
  {
    company: 'Ealana',
    role: 'Software Engineering Intern',
    period: 'Jan 2026 — May 2026',
    current: false,
    desc: 'Implemented WhatsApp integration to support parallel email and WhatsApp updates.<br/>Integrated a PostgreSQL/pgvector graph database for searching and sourcing candidates.<br/>Revamped the company’s public pages to improve UX and visual consistency.',
  },
  {
    company: 'Aeternik',
    role: 'Software Engineering Intern',
    period: 'Sep 2025 — Jan 2026',
    current: false,
    desc: 'Architected and containerized a microservices-based AI backend using Go, Python, and Docker.<br/>Developed an advanced RAG system for production using a modular framework.<br/>Implemented caching and feedback loops to reduce latency and hallucinations.',
  },
  {
    company: 'NALCO',
    role: 'Software Engineering Intern',
    period: 'June 2025',
    current: false,
    desc: 'Created an internal RAG tool using a FastAPI/PostgreSQL backend with an HTML/CSS/JavaScript frontend.<br/>Implemented PDF ingestion, chunking, and embedding using Sentence Transformers for vector search.',
  },
  {
    company: 'K J Somaiya College of Engineering',
    role: 'ML Research Intern',
    period: 'Feb 2025 — Present',
    current: false,
    desc: 'Managed data pipelines for agricultural datasets to support machine learning applications.<br/>Built and optimized predictive machine learning models for accuracy and interpretability.',
  },
  {
    company: 'SMLRA',
    role: 'Committee Member',
    period: 'Aug 2024 — May 2025',
    current: false,
    desc: 'Conducted research on legal document summarization to explore innovative applications of technology.<br/>Contributed to event management by preparing presentations and assisting in hosting activities.<br/>Created engaging social media stories such as Fact Friday and ML Monday to share knowledge and drive community interaction.',
  },
  {
    company: 'Secuodsoft Technologies',
    role: 'Python Developer Intern',
    period: 'Dec 2024',
    current: false,
    desc: 'Developed backend features using Django and MySQL.<br/>Implemented frontend components using JavaScript and Bootstrap.<br/>Managed static and media files for application assets and uploads.',
  },
]

function renderBulletPoints(htmlLikeText: string) {
  const points = htmlLikeText.split(/<br\s*\/?>/gi).filter(p => p.trim())
  return (
    <ul className="flex flex-col gap-2 list-none m-0 p-0">
      {points.map((point, i) => (
        <li key={i} className="flex items-start gap-2">
          <span className="mt-[7px] shrink-0 w-[5px] h-[5px] rounded-full" style={{ background: 'var(--accent)' }} />
          <span>{point.trim()}</span>
        </li>
      ))}
    </ul>
  )
}

export default function Experience() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null)

  const toggle = (i: number) => {
    setExpandedIndex(prev => (prev === i ? null : i))
  }

  return (
    <section className="py-20 border-b" style={{ borderColor: 'var(--border)' }} id="experience">
      <div className="max-w-[1060px] mx-auto px-5 md:px-8">
        <div className="mb-10">
          <h2
            className="text-[clamp(24px,3vw,32px)] tracking-[3px] uppercase font-medium"
            style={{ color: 'var(--fg)' }}
          >
            Experience
          </h2>
          <span className="text-[12px] mt-1 inline-block" style={{ color: 'var(--accent)' }}>8 roles</span>
        </div>

        <ScrollReveal stagger>
          <div
            className="flex flex-col"
            style={{ gap: '1px', background: 'var(--border)', border: '1px solid var(--border)' }}
          >
            {experiences.map((exp, i) => {
              const isOpen = expandedIndex === i
              return (
                <div
                  key={i}
                  className="reveal sweep-hover flex flex-col gap-3 p-6 px-7 relative cursor-pointer select-none"
                  style={{ background: 'var(--bg2)' }}
                  onClick={() => toggle(i)}
                  onMouseEnter={e =>
                    (e.currentTarget.style.background =
                      'color-mix(in srgb, var(--bg2) 92%, var(--accent) 8%)')
                  }
                  onMouseLeave={e => (e.currentTarget.style.background = 'var(--bg2)')}
                >
                  {exp.current && (
                    <div
                      className="absolute top-0 left-0 w-[3px] h-full"
                      style={{ background: 'var(--accent)' }}
                    />
                  )}
                  <div className="flex items-baseline gap-x-3">
                    <div className="flex flex-wrap items-baseline gap-x-3 flex-1">
                      <span
                        className="text-[22px] md:text-[26px] tracking-wider"
                        style={{
                          fontFamily: "'Geist Pixel', 'Geist Mono', monospace",
                          color: 'var(--fg)',
                        }}
                      >
                        {exp.role}
                      </span>
                      <span
                        className="text-[15px] md:text-[18px] italic"
                        style={{ color: 'var(--accent)' }}
                      >
                        @ {exp.company}
                      </span>
                    </div>
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="shrink-0 transition-transform duration-150"
                      style={{
                        color: 'var(--dim)',
                        transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)',
                      }}
                    >
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </div>
                  <div
                    className="text-[12px] tracking-[2px] uppercase"
                    style={{ color: 'var(--dim)' }}
                  >
                    {exp.period}
                  </div>
                  <div
                    className="overflow-hidden transition-all duration-150 ease-in-out"
                    style={{
                      maxHeight: isOpen ? '500px' : '0px',
                      opacity: isOpen ? 1 : 0,
                    }}
                  >
                    <div
                      className="text-[15px] leading-[1.7] mt-1"
                      style={{ color: 'var(--dim)' }}
                    >
                      {renderBulletPoints(exp.desc)}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </ScrollReveal>
      </div>
    </section>
  )
}
